[package]
name = "tls"
version = "0.1.0"
edition = "2021"
authors = ["user <email>"]

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
rustls = "0.20.8"
rustls-pemfile = "1.0.2"
